baseURL = 'https://pierangeloc.github.io/'
languageCode = 'en-us'
title = 'BLOG'
theme = 'HugoTeX'

[pagination]
  pagerSize = 3

[Params.author]
  name = "Pierangelo Cecchetto"
  abstract = """
  I'm a software engineer living in Amsterdam. Interested in Functional Programming techniques, mostly using in Scala, but also and Rust and Typescript.
  """

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "paraiso-dark"

[Params]
  lightmode = true
